### ISSUE TITLE
[BUG] Unable to toggle on/off duty

### ISSUE THREAD

**Issue by Wafflzdev** [CoZmoTheGod/qb-policejob#1]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to duty location
2. Attempt to 3rd eye or press E
3. Nothing comes up to toggle duty

**Expected behavior**
Should be able to go on/off duty

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 8/31/2022
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] No
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**
In the client/job.lua, line 530, still set to job = "police" which prevents other LEO departments from going on duty.  Suggest changing 
to something like this for line 530

                        job = {["lspd"] = 0, ["bcso"] = 0}

**Comment by CoZmoTheGod** [comment]
Issue has been fixed
